### ISSUE TITLE
UX: редактирование несуществующей сессии

### ISSUE THREAD

**Issue by dimaweber** [t-OmmY/shooting_gallery#3]
Удалить все сессии.
В окне выбора сессии пустой комбобокс и кнопка Choose session -- её можно нажать, добавить серию, добавить дырку к серии.

Предложение по исправлению: кнопку Choose Session делать доступной только когда в выпадающей списке выбрана какая то сессия. аналогично с ериями и дырками -- кнопки Watch XXX -- делать доступными только когда ХХХ выбрано

**Comment by t-OmmY** [comment]
исправлено

**Comment by t-OmmY** [comment]
Если нету сессий/серий/выстрелов - вместо списка и кнопки будет надпись - нету
