### ISSUE TITLE
UX: сохранение последней серии

### ISSUE THREAD

**Issue by dimaweber** [t-OmmY/shooting_gallery#4]
Невозможно сохранить последнюю серию.
Кнопка save and add another -- добавляет новую пустую серию.
Кнопка finished serie -- не сохраняет введённую дырку.

**Comment by t-OmmY** [comment]
Исправлено. Кнопка save and add another заменена на кнопку save. Она записывает данные и переводит на выбранную серию, от туда есть возможность уже делать что нам интересно
