### ISSUE TITLE
UX: id не должны быть видны

### ISSUE THREAD

**Issue by dimaweber** [t-OmmY/shooting_gallery#6]
все id -- сессии, серии, дырки -- это внутренняя информация базы данных. Для пользователя они не существуют. Если надо как то отличать серии между собой (например -- для выбора сессии в первом окне) -- надо использовать имя сессии/серии.

для сортировки серий надо использовать порядковый номер серии.

**Comment by t-OmmY** [comment]
а вот это плохо)) у меня все построено именно на ИД

**Comment by t-OmmY** [comment]
Исправлено костылями - на данный момент я просто сделал не видимым эти параметры - но это криво. Будет время и вдохновение - я переделаю. Просто там переделывать нужно все запросы скл....
