### ISSUE TITLE
UX: редактирование полей

### ISSUE THREAD

**Issue by dimaweber** [t-OmmY/shooting_gallery#7]
Для поля таблицы калибр надо добавить возможность добавления/удаления/редактирование записей. Предусмотреть возможность добавления нового калибра со страницы добавления сессии.

**Comment by t-OmmY** [comment]
Реализован отдельный контроллер для редактирования данных из дополнительных таблиц, таких как цвет, калибр, вид стрельбы, прицелы, стрелки и виды целей.
Прошу еще раз уточнить, что именно нужно
